h_hyperion_off: '/config/hyperion/on.sh'
h_mood_blobs_blue: '/config/hyperion/effects.sh "Blue mood blobs"'
h_knight_rider: '/config/hyperion/effects.sh "Knight rider"'
h_mood_blobs_cold: '/config/hyperion/effects.sh "Cold mood blobs"'
h_mood_blobs_full_color: '/config/hyperion/effects.sh "Full color mood blobs"'
h_mood_blobs_green: '/config/hyperion/effects.sh "Green mood blobs"'
h_mood_blobs_red: '/config/hyperion/effects.sh "Red mood blobs"'
h_mood_blobs_warm: '/config/hyperion/effects.sh "Warm mood blobs"'
h_rainbow_mood: '/config/hyperion/effects.sh "Rainbow mood"'
h_rainbow_swirl: '/config/hyperion/effects.sh "Rainbow swirl fast"'
h_snake: '/config/hyperion/effects.sh "Snake"'
h_strobe_blue: '/config/hyperion/effects.sh "Strobe blue"'
h_strobe_raspberry: '/config/hyperion/effects.sh "Strobe Raspbmc"'
h_strobe_white: '/config/hyperion/effects.sh "Strobe white"'
h_cinema_dim_lights: '/config/hyperion/effects.sh "Cinema dim lights"'
h_cinema_brighten_lights: '/config/hyperion/effects.sh "Cinema brighten lights"'
h_police_lights_single: '/config/hyperion/effects.sh "Police Lights Single"'
h_police_lights_solid: '/config/hyperion/effects.sh "Police Lights Solid"'
h_random: '/config/hyperion/effects.sh "Random"'
h_running_dots: '/config/hyperion/effects.sh "Running dots"'
h_system_shutdown: '/config/hyperion/effects.sh "System Shutdown"'
h_sparks_color: '/config/hyperion/effects.sh "Sparks Color"'
h_sparks: '/config/hyperion/effects.sh "Sparks"'
h_color_traces: '/config/hyperion/effects.sh "Color traces"'
